### ISSUE TITLE
Tooltip not show

### ISSUE THREAD

**Issue by tuemaytinh1981** [davigmacode/flutter_chips_choice#11]
I have code: ...
choiceItems: C2Choice.listFrom<String, String>(
                    source: options,
                    value: (i, v) => v,
                    label: (i, v) => v,
                    tooltip: (i, v) => v,
                  ),
...
tooltip not show ???

**Comment by davigmacode** [comment]
To be honest the parameter tooltip was not well tested when I released version 2.0.0, I just looked at the parameter tooltip in the `RawChip` class and added it to the `C2Choice` class.

I think this is a bug with Flutter itself (I use flutter stable v1.20.3), because it doesn't work either when using `ChoiceChip` or `FilterChip`, after seeing [this code](https://github.com/flutter/flutter/blob/f30b7f4db93ee747cd727df747941a28ead25ff5/packages/flutter/lib/src/material/chip.dart#L1887) it turns out that the tooltip parameter only works on Chip by filling in the `onPressed` parameter instead of `onSelected`, lucky `RawChip` has `onPressed`, so I've fixed it, please upgrade to version 2.0.1

Thank you for reporting this issue
